export const PERMISSIONS = {
  USERS_VIEW: "users.view",
  USERS_SUSPEND: "users.suspend",

  OWNERS_VIEW: "owners.view",
  OWNERS_VERIFY: "owners.verify",

  PROPERTIES_VIEW: "properties.view",
  PROPERTIES_CREATE: "properties.create",
  PROPERTIES_UPDATE: "properties.update",
  PROPERTIES_APPROVE: "properties.approve",
  PROPERTIES_SUSPEND: "properties.suspend",

  BOOKINGS_VIEW: "bookings.view",
  BOOKINGS_MANAGE: "bookings.manage",
  BOOKINGS_CANCEL: "bookings.cancel",

  TICKETS_VIEW: "tickets.view",
  TICKETS_RESPOND: "tickets.respond",
  TICKETS_ESCALATE: "tickets.escalate",

  PAYMENTS_VIEW: "payments.view",
  REFUNDS_REQUEST: "refunds.request",
  REFUNDS_APPROVE: "refunds.approve",
  SETTLEMENTS_MANAGE: "settlements.manage",

  STAFF_VIEW: "staff.view",
  STAFF_MANAGE: "staff.manage",

  REPORTS_VIEW: "reports.view",
  REPORTS_EXPORT: "reports.export",

  SETTINGS_MANAGE: "settings.manage",
  AUDIT_LOGS_VIEW: "audit_logs.view",
};

export const ROLE_PERMISSIONS = {
  customer: [],

  owner: [
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.PROPERTIES_CREATE,
    PERMISSIONS.PROPERTIES_UPDATE,
    PERMISSIONS.BOOKINGS_VIEW,
    PERMISSIONS.TICKETS_VIEW,
    PERMISSIONS.TICKETS_RESPOND,
    PERMISSIONS.PAYMENTS_VIEW,
  ],

  support: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.OWNERS_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.BOOKINGS_VIEW,
    PERMISSIONS.TICKETS_VIEW,
    PERMISSIONS.TICKETS_RESPOND,
    PERMISSIONS.TICKETS_ESCALATE,
    PERMISSIONS.REFUNDS_REQUEST,
  ],

  property_admin: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.OWNERS_VIEW,
    PERMISSIONS.OWNERS_VERIFY,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.PROPERTIES_APPROVE,
    PERMISSIONS.PROPERTIES_SUSPEND,
    PERMISSIONS.TICKETS_VIEW,
    PERMISSIONS.TICKETS_RESPOND,
    PERMISSIONS.REPORTS_VIEW,
  ],

  booking_manager: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.OWNERS_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.BOOKINGS_VIEW,
    PERMISSIONS.BOOKINGS_MANAGE,
    PERMISSIONS.BOOKINGS_CANCEL,
    PERMISSIONS.TICKETS_VIEW,
    PERMISSIONS.TICKETS_RESPOND,
    PERMISSIONS.REFUNDS_REQUEST,
    PERMISSIONS.REPORTS_VIEW,
  ],

  finance_manager: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.OWNERS_VIEW,
    PERMISSIONS.BOOKINGS_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.REFUNDS_REQUEST,
    PERMISSIONS.REFUNDS_APPROVE,
    PERMISSIONS.SETTLEMENTS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  operations_manager: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_SUSPEND,
    PERMISSIONS.OWNERS_VIEW,
    PERMISSIONS.OWNERS_VERIFY,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.PROPERTIES_CREATE,
    PERMISSIONS.PROPERTIES_UPDATE,
    PERMISSIONS.PROPERTIES_APPROVE,
    PERMISSIONS.PROPERTIES_SUSPEND,
    PERMISSIONS.BOOKINGS_VIEW,
    PERMISSIONS.BOOKINGS_MANAGE,
    PERMISSIONS.BOOKINGS_CANCEL,
    PERMISSIONS.TICKETS_VIEW,
    PERMISSIONS.TICKETS_RESPOND,
    PERMISSIONS.TICKETS_ESCALATE,
    PERMISSIONS.REFUNDS_REQUEST,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.AUDIT_LOGS_VIEW,
  ],

  super_admin: Object.values(PERMISSIONS),
};

export const USER_ROLES = Object.keys(ROLE_PERMISSIONS);